@echo off
rem Packages a clean, portable copy of this project -- your code, clips database,
rem transcripts and cookies -- WITHOUT the machine-specific build output (node_modules,
rem the compiled pot-provider, the Python venv, yt-dlp.exe) and WITHOUT the downloaded
rem source videos (sources/), which are the biggest thing here and easy to re-fetch if
rem ever needed. The machine-specific stuff gets regenerated by setup.bat on the new PC
rem instead of being copied, which is what avoids the "worked on the old PC, broken on
rem the new one" native-binary problem.
setlocal
cd /d "%~dp0"
title Podcast Clipper - Export for new PC

set "DEST=%~dp0..\podcast-clipper-portable"
if exist "%DEST%" rd /s /q "%DEST%"

echo Copying project to %DEST% ...
robocopy "%~dp0." "%DEST%" /E ^
  /XD node_modules pot-provider bin tmp .venv .claude sources ^
  /XF *.db-shm *.db-wal
rem robocopy's success exit codes are 0-7, not just 0
if errorlevel 8 goto :fail

echo.
echo Done. A clean copy is ready at:
echo   %DEST%
echo.
echo Copy that whole "podcast-clipper-portable" folder to the new PC (USB drive, Google
echo Drive, etc.), then on the new PC double-click setup.bat inside it.
pause
exit /b 0

:fail
echo.
echo Copy failed -- see the error above.
pause
exit /b 1
